# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

CategoriesFeedSource.create!([
  {feed_source_id: 22, category_id: 5},
  {feed_source_id: 23, category_id: 5},
  {feed_source_id: 10, category_id: 2},
  {feed_source_id: 1, category_id: 1},
  {feed_source_id: 22, category_id: 5},
  {feed_source_id: 23, category_id: 5},
  {feed_source_id: 10, category_id: 2},
  {feed_source_id: 1, category_id: 1},
  {feed_source_id: 7, category_id: 6},
  {feed_source_id: 11, category_id: 6},
  {feed_source_id: 12, category_id: 6},
  {feed_source_id: 2, category_id: 4},
  {feed_source_id: 5, category_id: 1},
  {feed_source_id: 13, category_id: 6},
  {feed_source_id: 6, category_id: 3},
  {feed_source_id: 8, category_id: 2},
  {feed_source_id: 15, category_id: 1},
  {feed_source_id: 16, category_id: 1},
  {feed_source_id: 14, category_id: 6},
  {feed_source_id: 24, category_id: 2},
  {feed_source_id: 25, category_id: 2},
  {feed_source_id: 3, category_id: 4},
  {feed_source_id: 20, category_id: 1},
  {feed_source_id: 9, category_id: 4},
  {feed_source_id: 4, category_id: 4},
  {feed_source_id: 17, category_id: 1},
  {feed_source_id: 18, category_id: 1},
  {feed_source_id: 19, category_id: 3},
  {feed_source_id: 21, category_id: 5},
  {feed_source_id: 26, category_id: 5},
  {feed_source_id: 27, category_id: 5}
])
Category.create!([
  {name: "News"},
  {name: "Tech"},
  {name: "Sports"},
  {name: "Local"},
  {name: "Foreign"},
  {name: "Entertainment"}
])
FeedItem.create!([
  {feed_source_id: 20, identifier: "http://www.economist.com/news/international/21701723-britain-and-european-union-prepare-divorce-many-their-citizens-contemplate?fsrc=rss", title: "Get hitched or hike", url: "http://www.economist.com/news/international/21701723-britain-and-european-union-prepare-divorce-many-their-citizens-contemplate?fsrc=rss", description: "<p><div class=\"content-image-full\"><img src=\"http://cdn.static-economist.com/sites/default/files/imagecache/full-width/images/2016/07/articles/main/20160709_ird002.jpg\" alt=\"\" title=\"\"  width=\"595\" height=\"335\" /></div></p><p>DELPHINE was born in Jersey, a crown dependency of the United Kingdom, and holds a British passport. She and her Mexican boyfriend, José, intend to move to Paris from Mexico. When she heard that Britain had voted to leave the European Union, it threw those plans into doubt. Would she still be entitled to live in France? As she fretted, José sent her a message: “I guess you’ll have to marry me, then.” He has French citizenship, passed down from a French grandmother via his mother. After Brexit he will remain an EU citizen. Though he was joking, the pair are now seriously considering tying the knot.</p><p>Migrants between Britain and the 27 countries that will make up the post-Brexit EU fear losing not only the right to move freely, but to stay put. Theresa May, the front-runner to replace the prime minister, David Cameron, who is stepping down in the wake of the Leave vote, says the residency status of EU citizens in Britain may form part of the Brexit negotiations. For many, such comments have kicked off a search to guarantee they can stay where they are living. Neil White, a lawyer, says his firm, 1st4immigration, has been inundated with people...<a href=\"http://www.economist.com/news/international/21701723-britain-and-european-union-prepare-divorce-many-their-citizens-contemplate?fsrc=rss\">Continue reading</a>", author: "The Economist online", pub_date: "2016-07-06 15:27:14", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/news/international/21701949-battle-downing-street-hots-up-britain-race-tory-leader-whittled-down-two?fsrc=rss", title: "China&#039;s restless millions", url: "http://www.economist.com/news/international/21701949-battle-downing-street-hots-up-britain-race-tory-leader-whittled-down-two?fsrc=rss", description: "<p><span data-sheets-value=\"&quot;The battle for Downing Street hots up in Britain as the race for Tory leader is whittled down to two. As China&#039;s middle class gets bigger and richer, they pose a growing threat to the ruling Communist Party. Finally, Zimbabwe wants a $1 billion bail-out from the IMF. Our Africa editor thinks they shouldn&#039;t get it. Christopher Lockwood hosts.&quot;}\" data-sheets-userformat=\"&quot;arial, sans-serif&quot;}\"><object id=\"myExperience_1425961410001_5027937683001\" class=\"BrightcoveExperience\"><param name=\"bgcolor\" value=\"#FFFFFF\" /><param name=\"isUI\" value=\"true\" /><param name=\"isVid\" value=\"true\" /><param name=\"dynamicStreaming\" value=\"true\" /><param name=\"autoStart\" value=\"true\" /><param name=\"wmode\" value=\"opaque\" /><param name=\"templateLoadHandler\" value=\"ECOmnitureBrightCoveHandlers25fb37ea18f892013cd71b8a4f3c56e1.omnitureBCTemplateLoaded\" /><param name=\"handlerID\" value=\"ECOmnitureBrightCoveHandlers25fb37ea18f892013cd71b8a4f3c56e1\" /><param name=\"includeAPI\" value=\"true\" /><param name=\"linkBaseURL\" value=\"http://www.economist.com/sections/international/rss.xml\" /><param name=\"iid\" value=\"114623\" /><param name=\"vid\" value=\"5027937683001\" /><param name=\"pid\" value=\"1425961410001\" /><param name=\"key\" value=\"AQ~~,AAABDH-R__E~,dB4S9tmhdOo20g03jDsDgNBGDcclfHEU\" /><param name=\"cssclass\" value=\"\" /><param name=\"width\" value=\"595\" /><param...<a href=\"http://www.economist.com/news/international/21701949-battle-downing-street-hots-up-britain-race-tory-leader-whittled-down-two?fsrc=rss\">Continue reading</a>", author: "The Economist online", pub_date: "2016-07-08 16:59:25", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/news/international/21701753-countries-invented-points-based-immigration-systems-have-concluded-they-do-not?fsrc=rss", title: "What’s the point?", url: "http://www.economist.com/news/international/21701753-countries-invented-points-based-immigration-systems-have-concluded-they-do-not?fsrc=rss", description: "<p><div class=\"content-image-full\"><img src=\"http://cdn.static-economist.com/sites/default/files/imagecache/full-width/images/print-edition/20160709_IRD001_0.jpg\" alt=\"\" title=\"\"  width=\"595\" height=\"335\" /></div></p><p>BRITAIN’S Conservative Party was languishing in opposition when, in 2005, it hit upon a winning idea. If elected, it would introduce an “Australian-style points system” for work permits. So popular was the pitch that a Labour government created such a system three years later; the immigration minister, Liam Byrne, even flew to Sydney to launch the scheme, although it did not last long. Campaigners for Britain to leave the European Union repeated the promise this year. It was their most detailed policy proposal, and may well have carried them to victory.</p><p>“There’s something deep in the British psyche about the Australian system,” says Mr Byrne. But points-based immigration regimes look most attractive from a distance. The countries that invented them concluded some time ago that they are flawed, and have tweaked them radically. They have also discovered that points systems do not completely cure xenophobia.</p><p></p><p>Canada created the world’s first points system, in 1967. Would-be immigrants who scored highest on youth, education, experience and fluency in English or French were offered permanent residency. In 1979 Australia created a...<a href=\"http://www.economist.com/news/international/21701753-countries-invented-points-based-immigration-systems-have-concluded-they-do-not?fsrc=rss\">Continue reading</a>", author: "The Economist online", pub_date: "2016-07-07 15:00:58", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/news/international/21701864-anne-mcelvoy-hosts-diplomat-and-pioneer-liberal-interventionism-robert-cooper-explains-what?fsrc=rss", title: "Chilcot inquiry special", url: "http://www.economist.com/news/international/21701864-anne-mcelvoy-hosts-diplomat-and-pioneer-liberal-interventionism-robert-cooper-explains-what?fsrc=rss", description: "<p><object id=\"myExperience_1425961410001_5026410489001\" class=\"BrightcoveExperience\"><param name=\"bgcolor\" value=\"#FFFFFF\" /><param name=\"isUI\" value=\"true\" /><param name=\"isVid\" value=\"true\" /><param name=\"dynamicStreaming\" value=\"true\" /><param name=\"autoStart\" value=\"true\" /><param name=\"wmode\" value=\"opaque\" /><param name=\"templateLoadHandler\" value=\"ECOmnitureBrightCoveHandlersbbb45cdb7a753a29bd911fb741a0ddaa.omnitureBCTemplateLoaded\" /><param name=\"handlerID\" value=\"ECOmnitureBrightCoveHandlersbbb45cdb7a753a29bd911fb741a0ddaa\" /><param name=\"includeAPI\" value=\"true\" /><param name=\"linkBaseURL\" value=\"http://www.economist.com/sections/international/rss.xml\" /><param name=\"iid\" value=\"114579\" /><param name=\"vid\" value=\"5026410489001\" /><param name=\"pid\" value=\"1425961410001\" /><param name=\"key\" value=\"AQ~~,AAABDH-R__E~,dB4S9tmhdOo20g03jDsDgNBGDcclfHEU\" /><param name=\"cssclass\" value=\"\" /><param name=\"width\" value=\"595\" /><param name=\"height\" value=\"400\" /><param name=\"labels\" value=\"http://cdn.static-economist.com/sites/all/modules/custom/ec_brightcove/EcBcLables.xml\" /><param name=\"playerID\" value=\"1425961410001\" /><param name=\"playerKey\" value=\"AQ~~,AAABDH-R__E~,dB4S9tmhdOo20g03jDsDgNBGDcclfHEU\" /><param name=\"@videoPlayer\" value=\"5026410489001\" /></object>&nbsp;</p>", author: "The Economist online", pub_date: "2016-07-07 17:28:29", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/blogs/erasmus/2016/07/tony-blair-and-religion?fsrc=rss", title: "Tony Blair’s faith was long on zeal but light on self-awareness", url: "http://www.economist.com/blogs/erasmus/2016/07/tony-blair-and-religion?fsrc=rss", description: "<p><div class=\"content-image-full\"><img src=\"http://cdn.static-economist.com/sites/default/files/imagecache/full-width/images/2016/07/blogs/erasmus/20160709_blp529.jpg\" alt=\"\" title=\"\"  width=\"595\" height=\"335\" /></div></p><p>AS TONY BLAIR faces the verdict of the Chilcot enquiry on his actions in the Iraq war, there will be many questions about the role played by his spiritual convictions in the way he made decisions and presented them. The ex-prime minister’s faith is also the subject of an essay published this week by&nbsp;<a target=\"_blank\" href=\"http://www.theosthinktank.co.uk\">Theos</a>, a London-based religious think-tank; as part of a series of essays on heads of governments and their metaphysical beliefs.</p><p>Among world leaders of recent years, Mr Blair has a unique relationship with religion. His Christian faith is passionate, so much so that during his tenure as prime minister, from 1997 to 2007, his advisers had to restrain him from making overt references to God which would have sounded strange to many voters’ ears. Yet this was not the deep, unselfconscious faith of somebody who had emerged from a devout environment and therefore imbibed an intuitive feeling for the fixed meaning of sacraments and dogmas.</p><p>Rather, Mr Blair’s is an acquired religion. Mr Blair was strongly influenced by an Australian chaplain at Oxford University, Peter Thomson, and...<a href=\"http://www.economist.com/blogs/erasmus/2016/07/tony-blair-and-religion?fsrc=rss\">Continue reading</a>", author: "The Economist online", pub_date: "2016-07-06 11:12:21", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/blogs/erasmus/2016/07/religion-and-first-world-war?fsrc=rss", title: "The Great War changed religion and society, but not enough", url: "http://www.economist.com/blogs/erasmus/2016/07/religion-and-first-world-war?fsrc=rss", description: "<p><div class=\"content-image-full\"><img src=\"http://cdn.static-economist.com/sites/default/files/imagecache/full-width/images/2016/07/blogs/erasmus/20160702_blp534.jpg\" alt=\"\" title=\"\"  width=\"595\" height=\"335\" /></div></p><p>THERE have been solemn gatherings&nbsp;in&nbsp;the killing fields&nbsp;of France, acts of remembrance&nbsp;in London’s Parliament Square and Westminster Abbey, prayers at Manchester Cathedral.&nbsp;In all these&nbsp;commemorations of British losses at&nbsp;the Battle of the Somme,&nbsp;which began 100 years ago, one&nbsp;of the&nbsp;implied signals&nbsp;was a&nbsp;reassuring one: whatever chaos may&nbsp;rage&nbsp;in the world,&nbsp;great&nbsp;national institutions go on and on. They include&nbsp;the royal family, the armed forces and their&nbsp;proud&nbsp;regiments,&nbsp;the Anglican church and its archbishops. With the confidence&nbsp;of a nation&nbsp;that has no recent experience of&nbsp;occupation or revolution,&nbsp;Britain’s masters of ceremony know how&nbsp;to proclaim&nbsp;the message&nbsp;that&nbsp;in a turbulent world, the&nbsp;essential never&nbsp;changes.</p><p>In reality of course, almost every aspect of human society began changing&nbsp;from the moment the first shot was&nbsp;fired in 1914.&nbsp;Old hierarchies crumbled, colonial relationships began loosening, and&nbsp;the role of religion in historically Christian...<a href=\"http://www.economist.com/blogs/erasmus/2016/07/religion-and-first-world-war?fsrc=rss\">Continue reading</a>", author: "The Economist online", pub_date: "2016-07-03 16:50:41", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/news/international/21701599-highlights-july-1st-2016-edition-audio?fsrc=rss", title: "Highlights from the July 1st 2016 edition, in audio", url: "http://www.economist.com/news/international/21701599-highlights-july-1st-2016-edition-audio?fsrc=rss", description: "<p><span>This week: Indian politicians facing off on Twitter, the trains with energy as freight, and a scramble for passports in Ireland</span></p><p><span><object id=\"myExperience_1425961410001_5020393994001\" class=\"BrightcoveExperience\"><param name=\"bgcolor\" value=\"#FFFFFF\" /><param name=\"isUI\" value=\"true\" /><param name=\"isVid\" value=\"true\" /><param name=\"dynamicStreaming\" value=\"true\" /><param name=\"autoStart\" value=\"true\" /><param name=\"wmode\" value=\"opaque\" /><param name=\"templateLoadHandler\" value=\"ECOmnitureBrightCoveHandlers7f4a7b4524ba4ff7d060f88e99566123.omnitureBCTemplateLoaded\" /><param name=\"handlerID\" value=\"ECOmnitureBrightCoveHandlers7f4a7b4524ba4ff7d060f88e99566123\" /><param name=\"includeAPI\" value=\"true\" /><param name=\"linkBaseURL\" value=\"http://www.economist.com/sections/international/rss.xml\" /><param name=\"iid\" value=\"114104\" /><param name=\"vid\" value=\"5020393994001\" /><param name=\"pid\" value=\"1425961410001\" /><param name=\"key\" value=\"AQ~~,AAABDH-R__E~,dB4S9tmhdOo20g03jDsDgNBGDcclfHEU\" /><param name=\"cssclass\" value=\"\" /><param name=\"width\" value=\"595\" /><param name=\"height\" value=\"400\" /><param name=\"labels\" value=\"http://cdn.static-economist.com/sites/all/modules/custom/ec_brightcove/EcBcLables.xml\" /><param name=\"playerID\" value=\"1425961410001\" /><param name=\"playerKey\" value=\"AQ~~,AAABDH-R__E~,dB4S9tmhdOo20g03jDsDgNBGDcclfHEU\" /><param...<a href=\"http://www.economist.com/news/international/21701599-highlights-july-1st-2016-edition-audio?fsrc=rss\">Continue reading</a>", author: "The Economist online", pub_date: "2016-07-01 15:36:31", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/news/international/21701583-brexit-vote-has-convulsed-party-politics-uk-who-will-rise-top-tory-party?fsrc=rss", title: "Tory Tussle", url: "http://www.economist.com/news/international/21701583-brexit-vote-has-convulsed-party-politics-uk-who-will-rise-top-tory-party?fsrc=rss", description: "<p><object id=\"myExperience_1425961410001_5016654851001\" class=\"BrightcoveExperience\"><param name=\"bgcolor\" value=\"#FFFFFF\" /><param name=\"isUI\" value=\"true\" /><param name=\"isVid\" value=\"true\" /><param name=\"dynamicStreaming\" value=\"true\" /><param name=\"autoStart\" value=\"true\" /><param name=\"wmode\" value=\"opaque\" /><param name=\"templateLoadHandler\" value=\"ECOmnitureBrightCoveHandlers55b3def35cd7186b5e9067a5428c167e.omnitureBCTemplateLoaded\" /><param name=\"handlerID\" value=\"ECOmnitureBrightCoveHandlers55b3def35cd7186b5e9067a5428c167e\" /><param name=\"includeAPI\" value=\"true\" /><param name=\"linkBaseURL\" value=\"http://www.economist.com/sections/international/rss.xml\" /><param name=\"iid\" value=\"114072\" /><param name=\"vid\" value=\"5016654851001\" /><param name=\"pid\" value=\"1425961410001\" /><param name=\"key\" value=\"AQ~~,AAABDH-R__E~,dB4S9tmhdOo20g03jDsDgNBGDcclfHEU\" /><param name=\"cssclass\" value=\"\" /><param name=\"width\" value=\"595\" /><param name=\"height\" value=\"400\" /><param name=\"labels\" value=\"http://cdn.static-economist.com/sites/all/modules/custom/ec_brightcove/EcBcLables.xml\" /><param name=\"playerID\" value=\"1425961410001\" /><param name=\"playerKey\" value=\"AQ~~,AAABDH-R__E~,dB4S9tmhdOo20g03jDsDgNBGDcclfHEU\" /><param name=\"@videoPlayer\" value=\"5016654851001\" /></object></p>", author: "The Economist online", pub_date: "2016-07-01 11:50:48", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/news/international/21701483-great-cities-africa-and-asia-are-spreading-fast-and-bizarre-ways-bourgeois?fsrc=rss", title: "Bourgeois shanty towns", url: "http://www.economist.com/news/international/21701483-great-cities-africa-and-asia-are-spreading-fast-and-bizarre-ways-bourgeois?fsrc=rss", description: "<p><div class=\"content-image-full\"><img src=\"http://cdn.static-economist.com/sites/default/files/imagecache/full-width/images/print-edition/20160702_IRP001_0.jpg\" alt=\"\" title=\"\"  width=\"595\" height=\"335\" /></div></p><p>INSIDE, Essa Mwaitulo’s house on the edge of Dar es Salaam is the picture of middle-class African domesticity. The sofas are luxurious; the curtains are golden; the walls are shocking pink; the floor, on which Ms Mwaitulo’s daughter has crashed out, is polished stone. “We are free, actually,” she says contentedly, sounding like anyone who has ever moved from a rented city-centre flat to a suburban house of her own. “I can do whatever I want.”</p><p>Step outside, though, and the impression of harmony and control dissolves. The scene around Ms Mwaitulo’s house in Mikwambe is chaotic. Houses are rising higgledy-piggledy. Many are half-finished and look abandoned, although they are not: one has no floor and a tree growing inside. What appears to be a small village square turns out to be a plot on which the owner has not yet got around to building. The neighbourhood has only one paved road, no central water supply and no sewer. It is a kind of bourgeois shanty town.</p><p></p><p>A huge and growing number of people live somewhere like Mikwambe. Between 2005 and 2015 the world’s cities swelled by about 750m people, according to the UN. More than...<a href=\"http://www.economist.com/news/international/21701483-great-cities-africa-and-asia-are-spreading-fast-and-bizarre-ways-bourgeois?fsrc=rss\">Continue reading</a>", author: "The Economist online", pub_date: "2016-06-30 14:59:19", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/news/international/21701454-rural-areas-are-turning-urban-far-faster-planners-expected-great-cities-africa?fsrc=rss", title: "The great cities of Africa and Asia are spreading fast, and in bizarre ways", url: "http://www.economist.com/news/international/21701454-rural-areas-are-turning-urban-far-faster-planners-expected-great-cities-africa?fsrc=rss", description: "<p><div class=\"content-image-full\"><img src=\"http://cdn.static-economist.com/sites/default/files/imagecache/full-width/images/2016/06/articles/main/20160702_irp001.jpg\" alt=\"\" title=\"\"  width=\"595\" height=\"335\" /></div></p><p>INSIDE, Essa Mwaitulo’s house on the edge of Dar es Salaam is the picture of middle-class African domesticity. The sofas are luxurious; the curtains are golden; the walls are shocking pink; the floor, on which Ms Mwaitulo’s daughter has crashed out, is polished stone. “We are free, actually,” she says contentedly, sounding like anyone who has ever moved from a rented city-centre flat to a suburban house of her own. “I can do whatever I want.”</p><p>Step outside, though, and the impression of harmony and control dissolves. The scene around Ms Mwaitulo’s house in Mikwambe is chaotic. Houses are rising higgledy-piggledy. Many are half-finished and look abandoned, although they are not: one has no floor and a tree growing inside. What appears to be a small village square turns out to be a plot on which the owner has not yet got around to building. The neighbourhood has only one paved road, no central water supply and no sewer. It is a kind of bourgeois shanty town.</p><p></p><p>A huge and growing number of people live somewhere like Mikwambe. Between 2005 and 2015 the world’s cities swelled by about 750m people, according to the UN. More than...<a href=\"http://www.economist.com/news/international/21701454-rural-areas-are-turning-urban-far-faster-planners-expected-great-cities-africa?fsrc=rss\">Continue reading</a>", author: "The Economist online", pub_date: "2016-06-29 15:04:16", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/news/international/21701452-gadgets-become-more-intelligent-should-we-embrace-smart-devices-or-fear-them-thomas-rid?fsrc=rss", title: "How will worries over technology shape our digital future?", url: "http://www.economist.com/news/international/21701452-gadgets-become-more-intelligent-should-we-embrace-smart-devices-or-fear-them-thomas-rid?fsrc=rss", description: "<p><object id=\"myExperience_1425961410001_5012081477001\" class=\"BrightcoveExperience\"><param name=\"bgcolor\" value=\"#FFFFFF\" /><param name=\"isUI\" value=\"true\" /><param name=\"isVid\" value=\"true\" /><param name=\"dynamicStreaming\" value=\"true\" /><param name=\"autoStart\" value=\"true\" /><param name=\"wmode\" value=\"opaque\" /><param name=\"templateLoadHandler\" value=\"ECOmnitureBrightCoveHandlers3be7841707eea32ae196031d98f2df80.omnitureBCTemplateLoaded\" /><param name=\"handlerID\" value=\"ECOmnitureBrightCoveHandlers3be7841707eea32ae196031d98f2df80\" /><param name=\"includeAPI\" value=\"true\" /><param name=\"linkBaseURL\" value=\"http://www.economist.com/sections/international/rss.xml\" /><param name=\"iid\" value=\"113992\" /><param name=\"vid\" value=\"5012081477001\" /><param name=\"pid\" value=\"1425961410001\" /><param name=\"key\" value=\"AQ~~,AAABDH-R__E~,dB4S9tmhdOo20g03jDsDgNBGDcclfHEU\" /><param name=\"cssclass\" value=\"\" /><param name=\"width\" value=\"595\" /><param name=\"height\" value=\"400\" /><param name=\"labels\" value=\"http://cdn.static-economist.com/sites/all/modules/custom/ec_brightcove/EcBcLables.xml\" /><param name=\"playerID\" value=\"1425961410001\" /><param name=\"playerKey\" value=\"AQ~~,AAABDH-R__E~,dB4S9tmhdOo20g03jDsDgNBGDcclfHEU\" /><param name=\"@videoPlayer\" value=\"5012081477001\" /></object></p></p>", author: "The Economist online", pub_date: "2016-06-29 14:49:33", enclosure: nil, guid: nil},
  {feed_source_id: 20, identifier: "http://www.economist.com/blogs/erasmus/2016/06/asylum-and-religious-knowledge?fsrc=rss", title: "Why religious persecution can be hard to test", url: "http://www.economist.com/blogs/erasmus/2016/06/asylum-and-religious-knowledge?fsrc=rss", description: "<p><div class=\"content-image-full\"><img src=\"http://cdn.static-economist.com/sites/default/files/imagecache/full-width/images/2016/06/blogs/erasmus/20160625_blp522_1.jpg\" alt=\"\" title=\"\"  width=\"595\" height=\"335\" /></div></p><p>WHEN a newly arrived migrant seeks asylum on grounds that going home would mean facing religous persecution, how can the host country test the sincerity of that claim? That is a hard question, especially if the migrant has only recently converted to a different faith. It’s also a very topical one, given the <a href=\"http://www.christianitytoday.com/gleanings/2015/november/is-germanys-refugee-crisis-muslim-mission-field.html\" target=\"_blank\">reports</a> that hundreds of newcomers in Germany and the Netherlands have switched from Islam to Christianity.&nbsp;If they come from countries where <a href=\"http://www.economist.com/news/middle-east-and-africa/21695542-penalties-turning-away-islam-can-be-quite-stringent-not-advised\">apostasy&nbsp;from Islam</a>&nbsp;incurs terrible consequences, even the death penalty,&nbsp;then they can make a strong case that&nbsp;their safety depends on finding a new&nbsp;home. So how can authorities tell&nbsp;if they have had a real change of heart or are simply&nbsp;looking&nbsp;for a new way to buttress their case?</p><p>According to a <a...<a href=\"http://www.economist.com/blogs/erasmus/2016/06/asylum-and-religious-knowledge?fsrc=rss\">Continue reading</a>", author: "The Economist online", pub_date: "2016-06-28 12:02:18", enclosure: nil, guid: nil}
])
FeedSource.create!([
  {title: "Ars Technica", feed_url: "http://feeds.arstechnica.com/arstechnica/index/", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/ars_technica.png", url: "http://arstechnica.com", last_refreshed: "2000-01-01 23:13:23"},
  {title: "xkcd.com", feed_url: "http://xkcd.com/rss.xml", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/xkcd.png", url: "http://xkcd.com/", last_refreshed: "2000-01-01 23:13:23"},
  {title: "Noticias más vistas | EL PAÍS", feed_url: "http://ep00.epimg.net/rss/tags/noticias_mas_vistas.xml", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/el_pais.png", url: "http://elpais.com/rss/tags/noticias_mas_vistas.xml", last_refreshed: "2000-01-01 23:03:14"},
  {title: "Slate Articles", feed_url: "http://feeds.slate.com/slate", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/slate.gif", url: "http://www.slate.com/articles.teaser.all.10.rss", last_refreshed: "2000-01-01 23:13:17"},
  {title: "News : NPR", feed_url: "http://www.npr.org/rss/rss.php?id=1001", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/npr.png", url: "http://www.npr.org/templates/story/story.php?storyId=1001", last_refreshed: "2000-01-01 23:13:23"},
  {title: "The Atlantic", feed_url: "http://www.theatlantic.com/feed/all/", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/the_atlantic.png", url: "http://www.theatlantic.com/", last_refreshed: "2000-01-01 20:27:43"},
  {title: "SFist", feed_url: "http://feeds.gothamistllc.com/SFist", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/sfist.jpg", url: "http://sfist.com/", last_refreshed: "2000-01-01 23:13:20"},
  {title: "Reuters: Top News", feed_url: "http://feeds.reuters.com/reuters/topNews", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/reuters.gif", url: "http://www.reuters.com", last_refreshed: "2000-01-01 23:13:24"},
  {title: "The Oatmeal - Comics, Quizzes, & Stories", feed_url: "http://feeds.feedburner.com/oatmealfeed", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/oatmeal.png", url: "http://theoatmeal.com/", last_refreshed: "2000-01-01 22:55:02"},
  {title: "ESPN.com - TOP", feed_url: "http://sports.espn.go.com/espn/rss/news", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/espn.jpg", url: "http://espn.go.com", last_refreshed: "2000-01-01 23:13:21"},
  {title: "Wait But Why", feed_url: "http://waitbutwhy.com/feed", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/wait_but_why.jpg", url: "http://waitbutwhy.com", last_refreshed: "2000-01-01 22:55:11"},
  {title: "紐約時報中文網 國際縱覽", feed_url: "http://cn.nytimes.com/rss/zh-hant/", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/ny_teims.png", url: "http://cn.nytimes.com", last_refreshed: "2000-01-01 23:13:25"},
  {title: "Bay Area News", feed_url: "http://www.sfgate.com/bayarea/feed/Bay-Area-News-429.php", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/mercury_news.jpg", url: "http://www.sfgate.com/bayarea/feed/Bay-Area-News-429.php", last_refreshed: "2000-01-01 22:19:15"},
  {title: "International", feed_url: "http://www.economist.com/sections/international/rss.xml", recommended: false, image_url: "https://placeimg.com/500/500/nature", url: "http://www.economist.com/sections/international/rss.xml", last_refreshed: "2000-01-01 22:00:40"},
  {title: "Indexed", feed_url: "http://thisisindexed.com/feed/", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/indexed.png", url: "http://thisisindexed.com", last_refreshed: "2000-01-01 22:55:17"},
  {title: "Boing Boing", feed_url: "http://boingboing.net/feed", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/boing_boing.png", url: "http://boingboing.net", last_refreshed: "2000-01-01 23:13:21"},
  {title: "Le Monde.fr - Actualité à la Une", feed_url: "http://www.lemonde.fr/rss/une.xml", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/le_monde.png", url: "http://www.lemonde.fr/rss/une.xml", last_refreshed: "2000-01-01 22:53:33"},
  {title: "WIRED", feed_url: "http://www.wired.com/feed/", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/wired.gif", url: "http://www.wired.com", last_refreshed: "2000-01-01 23:13:25"},
  {title: "PolitiCal - Los Angeles Times", feed_url: "http://www.latimes.com/local/political/rss2.0.xml", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/la_times_dark.png", url: "http://www.latimes.com/local/political/rss2.0.xml", last_refreshed: "2000-01-01 22:53:56"},
  {title: "TechCrunch", feed_url: "http://feeds.feedburner.com/TechCrunch/", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/tech_crunch.jpg", url: "https://techcrunch.com", last_refreshed: "2000-01-01 22:54:42"},
  {title: "The Verge -  All Posts", feed_url: "http://www.theverge.com/rss/index.xml", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/verge.png", url: "http://www.theverge.com/", last_refreshed: "2000-01-01 22:54:48"},
  {title: "Courrier international - Actualités France et Monde, vidéos, infographies", feed_url: "http://www.courrierinternational.com/feed/category/6261/rss.xml", recommended: false, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/courrier_international.jpg", url: "http://www.courrierinternational.com/", last_refreshed: "2000-01-01 22:02:15"},
  {title: "California", feed_url: "http://feeds.mercurynews.com/mngi/rss/CustomRssServlet/568/200755.xml", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/sf_gate.png", url: "http://www.mercurynews.com/california/", last_refreshed: "2000-01-01 23:13:22"},
  {title: "RFI - A La Une-RFI", feed_url: "http://www.rfi.fr/general/rss", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/rfi.png", url: "http://www.rfi.fr/RFI%20-%20A%20La%20Une/rss", last_refreshed: "2000-01-01 23:13:26"},
  {title: "nymag.com: Politics", feed_url: "http://nymag.com/rss/Politics.xml", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/new_york_magazine.png", url: "http://nymag.com", last_refreshed: "2000-01-01 21:57:21"},
  {title: "The New Yorker: Everything", feed_url: "http://www.newyorker.com/feed/everything", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/new_yorker.png", url: "http://www.newyorker.com/", last_refreshed: "2000-01-01 21:57:54"},
  {title: "Yahoo Sports", feed_url: "https://ca.sports.yahoo.com/blogs/rss.xml", recommended: true, image_url: "https://s3-us-west-1.amazonaws.com/aggregreater/yahoo.png", url: "https://ca.sports.yahoo.com", last_refreshed: nil}
])
Folder.create!([
  {name: "Local", user_id: 2},
  {name: "News", user_id: 2},
  {name: "Sports", user_id: 2},
  {name: "Tech", user_id: 2},
  {name: "Distractify", user_id: 2}
])
ReadFeedRecord.create!([
  {user_id: 2, feed_item_id: 136}
])
Subscription.create!([
  {folder_id: 1, user_id: 2, feed_source_id: 2},
  {folder_id: 3, user_id: 2, feed_source_id: 6},
  {folder_id: 5, user_id: 2, feed_source_id: 7},
  {folder_id: 1, user_id: 2, feed_source_id: 9},
  {folder_id: 4, user_id: 2, feed_source_id: 10},
  {folder_id: 5, user_id: 2, feed_source_id: 12},
  {folder_id: 2, user_id: 2, feed_source_id: 21},
  {folder_id: 4, user_id: 2, feed_source_id: 24},
  {folder_id: 2, user_id: 2, feed_source_id: 26},
  {folder_id: 2, user_id: 2, feed_source_id: 15},
  {folder_id: 2, user_id: 2, feed_source_id: 1},
  {folder_id: 2, user_id: 2, feed_source_id: 16}
])
User.create!([
  {username: "sillygoose", password_digest: "$2a$10$jo5lOeg3OPMuddCfj6clcuJirbtGXvR4ltlZ.Qxg2ssRMPb7shpRi", session_token: "NbF4pto1UY-GSWazTCLwYA"},
  {username: "demo", password_digest: "$2a$10$2Z5e1Td1kJkM8O54YQSXQOEG3jEUE4eK4Nj6rqKjnlnub.NRjHo9y", session_token: "3kiXPSaOml58E9zHWd30nQ"}
])
